#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NJSVER=$1
ARCH=$2
PLAT=$3


echo "Downloading NJS $1 $2 $3

if [ "$PLAT" == "sunos" ]; then
  wget -nc "http://nodejs.org/dist/v$NJSVER/node-v$NJSVER-sunos-$ARCH.tar.gz" -O src/node-$NJSVER-$ARCH.tar.gz
else
  wget -nc "http://nodejs.org/dist/v$NJSVER/node-v$NJSVER-linux-$ARCH.tar.gz" -O src/node-$NJSVER-$ARCH.tar.gz
fi


echo "Installing NJS $1 $2 $3"

if [ ! -e njs-files/$NJSVER-$ARCH ]; then
  tar -xzvf src/node-$NJSVER-$ARCH.tar.gz -C tmp
  mv tmp/node-$NJSVER-*-$ARCH njs-files/$NJSVER-$ARCH
fi

if [ ! -e lcb-files/src/$LCBVER-$ARCH ]; then
  tar -xzvf src/lcb-$LCBVER-src.tar.gz -C tmp
  mv tmp/libcouchbase-$LCBVER lcb-files/src/$LCBVER-$ARCH
fi
