#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LCBVER=$1
ARCH=$2
PLAT=$3


echo "Downloading LCB $1 $2 $3"
wget -nc "http://packages.couchbase.com/clients/c/libcouchbase-$LCBVER.tar.gz" -O src/lcb-$LCBVER-src.tar.gz


echo "Installing LCB $1 $2 $3"

if [ ! -e lcb-files/src/$LCBVER-$ARCH ]; then
  tar -xzvf src/lcb-$LCBVER-src.tar.gz -C tmp
  mv tmp/libcouchbase-$LCBVER lcb-files/src/$LCBVER-$ARCH
fi

if [ ! -e lcb-files/dist/$LCBVER-$ARCH/lib/libcouchbase.so ]; then
  mkdir -p lcb-files/build/$LCBVER-$ARCH
  mkdir -p lcb-files/dist/$LCBVER-$ARCH
  cd lcb-files/build/$LCBVER-$ARCH
  $MYDIR/lcb-files/src/$LCBVER-$ARCH/cmake/configure --disable-tests --disable-couchbasemock --disable-ssl --prefix=$MYDIR/lcb-files/dist/$LCBVER-$ARCH
  make && make install
  cd $MYDIR
fi
