#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ARCH=$1
PLAT=$2

echo "Installing libcouchbase $ARCH"
./lsetup_lcb 2.4.9 $ARCH $PLAT
./lsetup_lcb 2.5.3 $ARCH $PLAT

echo "Installing Node.js $ARCH"
./lsetup_njs njs 0.10.40 $ARCH $PLAT
./lsetup_njs njs 0.12.7 $ARCH $PLAT
./lsetup_njs iojs 1.0.4 $ARCH $PLAT
./lsetup_njs iojs 1.8.4 $ARCH $PLAT
./lsetup_njs iojs 2.4.0 $ARCH $PLAT
./lsetup_njs iojs 3.0.0 $ARCH $PLAT
./lsetup_njs njs 4.0.0 $ARCH $PLAT

echo "Installing PHP $ARCH"
./lsetup_php 5.6.7 $ARCH $PLAT
./lsetup_php 5.5.23 $ARCH $PLAT
./lsetup_php 5.4.39 $ARCH $PLAT
