#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NJSMODE=$1
NJSVER=$2
ARCH=$3
PLAT=$4


if [ "$PLAT" == "sunos" ]; then
  if [ "$NJSMODE" == "iojs" ]; then
    echo "Skipping NJS $1 $2 $3 $4 due to SmartOS"
    exit 0
  fi
fi


echo "Downloading NJS $1 $2 $3 $4"

DLHOST="http://nodejs.org/dist"
FILEPREFIX="node"
if [ "$NJSMODE" == "iojs" ]; then
  DLHOST="http://iojs.org/dist"
  FILEPREFIX="iojs"
fi

if [ "$PLAT" == "sunos" ]; then
  wget -nc "$DLHOST/v$NJSVER/$FILEPREFIX-v$NJSVER-sunos-$ARCH.tar.gz" -O src/$FILEPREFIX-v$NJSVER-$ARCH.tar.gz
else
  wget -nc "$DLHOST/v$NJSVER/$FILEPREFIX-v$NJSVER-linux-$ARCH.tar.gz" -O src/$FILEPREFIX-v$NJSVER-$ARCH.tar.gz
fi


echo "Installing NJS $1 $2 $3 $4"

if [ ! -e njs-files/$NJSVER-$ARCH ]; then
  tar -xzvf src/$FILEPREFIX-v$NJSVER-$ARCH.tar.gz -C tmp
  mv tmp/$FILEPREFIX-v$NJSVER-*-$ARCH njs-files/$NJSVER-$ARCH
fi
