#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. common/env

echo "Preparing"
mkdir tmp
mkdir src
mkdir lcb-files
mkdir lcb-files/build
mkdir lcb-files/src
mkdir php-files
mkdir php-files/build
mkdir php-files/deps
mkdir php-files/src
mkdir njs-files

if [ "$MACHINE_ARCH" == "x64" ]; then
  ./lsetup_all x64 $PLAT
  ./lsetup_all x86 $PLAT
fi
if [ "$MACHINE_ARCH" == "x86" ]; then
  ./lsetup_all x86 $PLAT
fi


echo "Cleaning Up"
rm -rf tmp
