#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LCBVER=$1
ARCH=$2

if [ ! -e lcb-files/src/$LCBVER-$ARCH ]; then
  tar -xzvf src/lcb-$LCBVER-src.tar.gz -C tmp
  mv tmp/libcouchbase-$LCBVER lcb-files/src/$LCBVER-$ARCH
fi

if [ ! -e lcb-files/build/$LCBVER-$ARCH/lib/libcouchbase.so ]; then
  mkdir lcb-files/build/$LCBVER-$ARCH
  cd lcb-files/build/$LCBVER-$ARCH
  $MYDIR/lcb-files/src/$LCBVER-$ARCH/cmake/configure --disable-tests --disable-couchbasemock --disable-ssl
  cd $MYDIR
fi
