#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. common/env

mkdir tmp
mkdir src
mkdir lcb-files
mkdir lcb-files/build
mkdir lcb-files/src
mkdir php-files
mkdir php-files/build
mkdir php-files/deps
mkdir php-files/src
mkdir njs-files

echo "downloading libcouchbase files..."
wget -nc "http://packages.couchbase.com/clients/c/libcouchbase-2.4.9.tar.gz" -O src/lcb-2.4.9-src.tar.gz

echo "downloading php files..."
if [ "$PLAT" == "sunos" ]; then
  echo "Not downloading PHP due to SmartOS"
else
  wget -nc "http://php.net/get/php-5.4.39.tar.bz2/from/this/mirror" -O src/php-src-5.4.39.tar.bz2
  wget -nc "http://php.net/get/php-5.5.23.tar.bz2/from/this/mirror" -O src/php-src-5.5.23.tar.bz2
  wget -nc "http://php.net/get/php-5.6.7.tar.bz2/from/this/mirror" -O src/php-src-5.6.7.tar.bz2
  wget -nc "https://phar.phpunit.de/phpunit.phar" -O src/php-phpunit.phar
  wget -nc "http://phpdoc.org/phpDocumentor.phar" -O src/php-phpdoc.phar
fi

echo "downloading nodejs files..."
if [ "$PLAT" == "sunos" ]; then
  wget -nc "http://nodejs.org/dist/v0.10.38/node-v0.10.38-sunos-$ARCH.tar.gz" -O src/node-0.10.38-$ARCH.tar.gz
  wget -nc "http://nodejs.org/dist/v0.12.2/node-v0.12.2-sunos-$ARCH.tar.gz" -O src/node-0.12.2-$ARCH.tar.gz
else
  wget -nc "http://nodejs.org/dist/v0.10.38/node-v0.10.38-linux-$ARCH.tar.gz" -O src/node-0.10.38-$ARCH.tar.gz
  wget -nc "http://nodejs.org/dist/v0.12.2/node-v0.12.2-linux-$ARCH.tar.gz" -O src/node-0.12.2-$ARCH.tar.gz
fi




echo "installing lcb files..."
./setup_installlcb 2.4.9 $ARCH

echo "installing nodejs files..."
if [ ! -e njs-files/0.10.38-$ARCH ]; then
  tar -xzvf src/node-0.10.38-$ARCH.tar.gz -C tmp
  mv tmp/node-v0.10.38-*-$ARCH njs-files/0.10.38-$ARCH
fi
if [ ! -e njs-files/0.12.2-$ARCH ]; then
  tar -xzvf src/node-0.12.2-$ARCH.tar.gz -C tmp
  mv tmp/node-v0.12.2-*-$ARCH njs-files/0.12.2-$ARCH
fi


echo "installing php files..."
if [ "$PLAT" == "sunos" ]; then
  echo "Not installing PHP due to SmartOS"
else
  ./setup_installphp 5.6.7 $ARCH
  ./setup_installphp 5.5.23 $ARCH
  ./setup_installphp 5.4.39 $ARCH
fi

rm -rf tmp
