#!/bin/bash

MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LCBVER=$1
ARCH=$2

if [ ! -e lcb-files/src/$LCBVER-$ARCH ]; then
  tar -xzvf src/lcb-$LCBVER-src.tar.gz -C tmp
  mv tmp/libcouchbase-$LCBVER lcb-files/src/$LCBVER-$ARCH
fi

if [ ! -e lcb-files/build/$LCBVER-$ARCH ]; then
  cd lcb-files/src/$LCBVER-$ARCH
  ./configure --disable-tests --disable-couchbasemock --enable-ssl=no --prefix=$MYDIR/lcb-files/build/$LCBVER-$ARCH
  make && make install
fi
